### ISSUE TITLE
AWS Lambda Container Images

### ISSUE THREAD

**Issue by james-coder** [shogo82148/p5-aws-lambda#49]
A few weeks ago, AWS released Container Images for AWS Lambda. https://aws.amazon.com/blogs/aws/new-for-aws-lambda-container-image-support/

Is there any way that AWS::Lambda can take advantage of this to allow larger perl code deployment?

Can I use the docker container from AWS::Lambda, extend it, upload to ACR, then use it to launch an AWS Lambda function? https://metacpan.org/pod/AWS::Lambda#Run-in-Local-using-Docker

**Comment by shogo82148** [comment]
> Is there any way that AWS::Lambda can take advantage of this to allow larger perl code deployment?

I guess that AWS::Lambda works on docker container images, but not tested yet.

> Can I use the docker container from AWS::Lambda, extend it, upload to ACR, then use it to launch an AWS Lambda function?

You can't use the images on https://hub.docker.com/r/shogo82148/p5-aws-lambda to launch functions, because these images use a special linux user [sbx_user1051](https://github.com/lambci/docker-lambda/blob/b25f2695dec37f4b25c71f33ae3166075df38b6a/provided.al2/run/Dockerfile#L11).

**Comment by shogo82148** [comment]
AWS::Lambda v0.0.23 and pre-built Docker images are now available 🎉 
https://metacpan.org/pod/AWS::Lambda#Use-Prebuilt-Docker-Images

Enjoy hacking!
